version: "3.4"
services:
  cyberbots:
    image: cyberbotics/webots:R2021a-ubuntu18.04
    volumes:
      - ./controllers:/opt/controllers
      - ./worlds:/opt/worlds
      - ./.docker:/usr/local/webbots



